development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: Eventbrite
  pool: 5
  username: walid
  password: walid

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: Eventbrite
  pool: 5
  username: walid
  password: walid

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: Eventbrite
  pool: 5
  username: walid
  password: walid